// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package jupiter

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// LifinityTokenSwap is the `lifinityTokenSwap` instruction.
type LifinityTokenSwap struct {
	InAmount         *uint64 `bin:"optional"`
	MinimumOutAmount *uint64
	PlatformFeeBps   *uint8

	// [0] = [] swapProgram
	//
	// [1] = [] authority
	//
	// [2] = [] amm
	//
	// [3] = [SIGNER] userTransferAuthority
	//
	// [4] = [WRITE] sourceInfo
	//
	// [5] = [WRITE] destinationInfo
	//
	// [6] = [WRITE] swapSource
	//
	// [7] = [WRITE] swapDestination
	//
	// [8] = [WRITE] poolMint
	//
	// [9] = [WRITE] feeAccount
	//
	// [10] = [] tokenProgram
	//
	// [11] = [] pythAccount
	//
	// [12] = [] pythPcAccount
	//
	// [13] = [WRITE] configAccount
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewLifinityTokenSwapInstructionBuilder creates a new `LifinityTokenSwap` instruction builder.
func NewLifinityTokenSwapInstructionBuilder() *LifinityTokenSwap {
	nd := &LifinityTokenSwap{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 14),
	}
	return nd
}

// SetInAmount sets the "inAmount" parameter.
func (inst *LifinityTokenSwap) SetInAmount(inAmount uint64) *LifinityTokenSwap {
	inst.InAmount = &inAmount
	return inst
}

// SetMinimumOutAmount sets the "minimumOutAmount" parameter.
func (inst *LifinityTokenSwap) SetMinimumOutAmount(minimumOutAmount uint64) *LifinityTokenSwap {
	inst.MinimumOutAmount = &minimumOutAmount
	return inst
}

// SetPlatformFeeBps sets the "platformFeeBps" parameter.
func (inst *LifinityTokenSwap) SetPlatformFeeBps(platformFeeBps uint8) *LifinityTokenSwap {
	inst.PlatformFeeBps = &platformFeeBps
	return inst
}

// SetSwapProgramAccount sets the "swapProgram" account.
func (inst *LifinityTokenSwap) SetSwapProgramAccount(swapProgram ag_solanago.PublicKey) *LifinityTokenSwap {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(swapProgram)
	return inst
}

// GetSwapProgramAccount gets the "swapProgram" account.
func (inst *LifinityTokenSwap) GetSwapProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAuthorityAccount sets the "authority" account.
func (inst *LifinityTokenSwap) SetAuthorityAccount(authority ag_solanago.PublicKey) *LifinityTokenSwap {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(authority)
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *LifinityTokenSwap) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetAmmAccount sets the "amm" account.
func (inst *LifinityTokenSwap) SetAmmAccount(amm ag_solanago.PublicKey) *LifinityTokenSwap {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(amm)
	return inst
}

// GetAmmAccount gets the "amm" account.
func (inst *LifinityTokenSwap) GetAmmAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetUserTransferAuthorityAccount sets the "userTransferAuthority" account.
func (inst *LifinityTokenSwap) SetUserTransferAuthorityAccount(userTransferAuthority ag_solanago.PublicKey) *LifinityTokenSwap {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(userTransferAuthority).SIGNER()
	return inst
}

// GetUserTransferAuthorityAccount gets the "userTransferAuthority" account.
func (inst *LifinityTokenSwap) GetUserTransferAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetSourceInfoAccount sets the "sourceInfo" account.
func (inst *LifinityTokenSwap) SetSourceInfoAccount(sourceInfo ag_solanago.PublicKey) *LifinityTokenSwap {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(sourceInfo).WRITE()
	return inst
}

// GetSourceInfoAccount gets the "sourceInfo" account.
func (inst *LifinityTokenSwap) GetSourceInfoAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetDestinationInfoAccount sets the "destinationInfo" account.
func (inst *LifinityTokenSwap) SetDestinationInfoAccount(destinationInfo ag_solanago.PublicKey) *LifinityTokenSwap {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(destinationInfo).WRITE()
	return inst
}

// GetDestinationInfoAccount gets the "destinationInfo" account.
func (inst *LifinityTokenSwap) GetDestinationInfoAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetSwapSourceAccount sets the "swapSource" account.
func (inst *LifinityTokenSwap) SetSwapSourceAccount(swapSource ag_solanago.PublicKey) *LifinityTokenSwap {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(swapSource).WRITE()
	return inst
}

// GetSwapSourceAccount gets the "swapSource" account.
func (inst *LifinityTokenSwap) GetSwapSourceAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetSwapDestinationAccount sets the "swapDestination" account.
func (inst *LifinityTokenSwap) SetSwapDestinationAccount(swapDestination ag_solanago.PublicKey) *LifinityTokenSwap {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(swapDestination).WRITE()
	return inst
}

// GetSwapDestinationAccount gets the "swapDestination" account.
func (inst *LifinityTokenSwap) GetSwapDestinationAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetPoolMintAccount sets the "poolMint" account.
func (inst *LifinityTokenSwap) SetPoolMintAccount(poolMint ag_solanago.PublicKey) *LifinityTokenSwap {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(poolMint).WRITE()
	return inst
}

// GetPoolMintAccount gets the "poolMint" account.
func (inst *LifinityTokenSwap) GetPoolMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetFeeAccount sets the "feeAccount" account.
func (inst *LifinityTokenSwap) SetFeeAccount(feeAccount ag_solanago.PublicKey) *LifinityTokenSwap {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(feeAccount).WRITE()
	return inst
}

// GetFeeAccount gets the "feeAccount" account.
func (inst *LifinityTokenSwap) GetFeeAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *LifinityTokenSwap) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *LifinityTokenSwap {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *LifinityTokenSwap) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

// SetPythAccount sets the "pythAccount" account.
func (inst *LifinityTokenSwap) SetPythAccount(pythAccount ag_solanago.PublicKey) *LifinityTokenSwap {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(pythAccount)
	return inst
}

// GetPythAccount gets the "pythAccount" account.
func (inst *LifinityTokenSwap) GetPythAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(11)
}

// SetPythPcAccount sets the "pythPcAccount" account.
func (inst *LifinityTokenSwap) SetPythPcAccount(pythPcAccount ag_solanago.PublicKey) *LifinityTokenSwap {
	inst.AccountMetaSlice[12] = ag_solanago.Meta(pythPcAccount)
	return inst
}

// GetPythPcAccount gets the "pythPcAccount" account.
func (inst *LifinityTokenSwap) GetPythPcAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(12)
}

// SetConfigAccount sets the "configAccount" account.
func (inst *LifinityTokenSwap) SetConfigAccount(configAccount ag_solanago.PublicKey) *LifinityTokenSwap {
	inst.AccountMetaSlice[13] = ag_solanago.Meta(configAccount).WRITE()
	return inst
}

// GetConfigAccount gets the "configAccount" account.
func (inst *LifinityTokenSwap) GetConfigAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(13)
}

func (inst LifinityTokenSwap) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_LifinityTokenSwap,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst LifinityTokenSwap) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *LifinityTokenSwap) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.MinimumOutAmount == nil {
			return errors.New("MinimumOutAmount parameter is not set")
		}
		if inst.PlatformFeeBps == nil {
			return errors.New("PlatformFeeBps parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.SwapProgram is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Amm is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.UserTransferAuthority is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.SourceInfo is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.DestinationInfo is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.SwapSource is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.SwapDestination is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.PoolMint is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.FeeAccount is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.PythAccount is not set")
		}
		if inst.AccountMetaSlice[12] == nil {
			return errors.New("accounts.PythPcAccount is not set")
		}
		if inst.AccountMetaSlice[13] == nil {
			return errors.New("accounts.ConfigAccount is not set")
		}
	}
	return nil
}

func (inst *LifinityTokenSwap) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("LifinityTokenSwap")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=3]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("        InAmount (OPT)", inst.InAmount))
						paramsBranch.Child(ag_format.Param("MinimumOutAmount", *inst.MinimumOutAmount))
						paramsBranch.Child(ag_format.Param("  PlatformFeeBps", *inst.PlatformFeeBps))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=14]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("          swapProgram", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("            authority", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("                  amm", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("userTransferAuthority", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("           sourceInfo", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("      destinationInfo", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("           swapSource", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("      swapDestination", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("             poolMint", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("                  fee", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("         tokenProgram", inst.AccountMetaSlice.Get(10)))
						accountsBranch.Child(ag_format.Meta("                 pyth", inst.AccountMetaSlice.Get(11)))
						accountsBranch.Child(ag_format.Meta("               pythPc", inst.AccountMetaSlice.Get(12)))
						accountsBranch.Child(ag_format.Meta("               config", inst.AccountMetaSlice.Get(13)))
					})
				})
		})
}

func (obj LifinityTokenSwap) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `InAmount` param (optional):
	{
		if obj.InAmount == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.InAmount)
			if err != nil {
				return err
			}
		}
	}
	// Serialize `MinimumOutAmount` param:
	err = encoder.Encode(obj.MinimumOutAmount)
	if err != nil {
		return err
	}
	// Serialize `PlatformFeeBps` param:
	err = encoder.Encode(obj.PlatformFeeBps)
	if err != nil {
		return err
	}
	return nil
}
func (obj *LifinityTokenSwap) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `InAmount` (optional):
	{
		ok, err := decoder.ReadBool()
		if err != nil {
			return err
		}
		if ok {
			err = decoder.Decode(&obj.InAmount)
			if err != nil {
				return err
			}
		}
	}
	// Deserialize `MinimumOutAmount`:
	err = decoder.Decode(&obj.MinimumOutAmount)
	if err != nil {
		return err
	}
	// Deserialize `PlatformFeeBps`:
	err = decoder.Decode(&obj.PlatformFeeBps)
	if err != nil {
		return err
	}
	return nil
}

// NewLifinityTokenSwapInstruction declares a new LifinityTokenSwap instruction with the provided parameters and accounts.
func NewLifinityTokenSwapInstruction(
	// Parameters:
	inAmount uint64,
	minimumOutAmount uint64,
	platformFeeBps uint8,
	// Accounts:
	swapProgram ag_solanago.PublicKey,
	authority ag_solanago.PublicKey,
	amm ag_solanago.PublicKey,
	userTransferAuthority ag_solanago.PublicKey,
	sourceInfo ag_solanago.PublicKey,
	destinationInfo ag_solanago.PublicKey,
	swapSource ag_solanago.PublicKey,
	swapDestination ag_solanago.PublicKey,
	poolMint ag_solanago.PublicKey,
	feeAccount ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	pythAccount ag_solanago.PublicKey,
	pythPcAccount ag_solanago.PublicKey,
	configAccount ag_solanago.PublicKey) *LifinityTokenSwap {
	return NewLifinityTokenSwapInstructionBuilder().
		SetInAmount(inAmount).
		SetMinimumOutAmount(minimumOutAmount).
		SetPlatformFeeBps(platformFeeBps).
		SetSwapProgramAccount(swapProgram).
		SetAuthorityAccount(authority).
		SetAmmAccount(amm).
		SetUserTransferAuthorityAccount(userTransferAuthority).
		SetSourceInfoAccount(sourceInfo).
		SetDestinationInfoAccount(destinationInfo).
		SetSwapSourceAccount(swapSource).
		SetSwapDestinationAccount(swapDestination).
		SetPoolMintAccount(poolMint).
		SetFeeAccount(feeAccount).
		SetTokenProgramAccount(tokenProgram).
		SetPythAccount(pythAccount).
		SetPythPcAccount(pythPcAccount).
		SetConfigAccount(configAccount)
}
