// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package jupiter

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// TokenSwap is the `tokenSwap` instruction.
type TokenSwap struct {
	InAmount         *uint64 `bin:"optional"`
	MinimumOutAmount *uint64
	PlatformFeeBps   *uint8

	// [0] = [] tokenSwapProgram
	//
	// [1] = [] tokenProgram
	//
	// [2] = [] swap
	//
	// [3] = [] authority
	//
	// [4] = [SIGNER] userTransferAuthority
	//
	// [5] = [WRITE] source
	//
	// [6] = [WRITE] swapSource
	//
	// [7] = [WRITE] swapDestination
	//
	// [8] = [WRITE] destination
	//
	// [9] = [WRITE] poolMint
	//
	// [10] = [WRITE] poolFee
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewTokenSwapInstructionBuilder creates a new `TokenSwap` instruction builder.
func NewTokenSwapInstructionBuilder() *TokenSwap {
	nd := &TokenSwap{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 11),
	}
	return nd
}

// SetInAmount sets the "inAmount" parameter.
func (inst *TokenSwap) SetInAmount(inAmount uint64) *TokenSwap {
	inst.InAmount = &inAmount
	return inst
}

// SetMinimumOutAmount sets the "minimumOutAmount" parameter.
func (inst *TokenSwap) SetMinimumOutAmount(minimumOutAmount uint64) *TokenSwap {
	inst.MinimumOutAmount = &minimumOutAmount
	return inst
}

// SetPlatformFeeBps sets the "platformFeeBps" parameter.
func (inst *TokenSwap) SetPlatformFeeBps(platformFeeBps uint8) *TokenSwap {
	inst.PlatformFeeBps = &platformFeeBps
	return inst
}

// SetTokenSwapProgramAccount sets the "tokenSwapProgram" account.
func (inst *TokenSwap) SetTokenSwapProgramAccount(tokenSwapProgram ag_solanago.PublicKey) *TokenSwap {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(tokenSwapProgram)
	return inst
}

// GetTokenSwapProgramAccount gets the "tokenSwapProgram" account.
func (inst *TokenSwap) GetTokenSwapProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *TokenSwap) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *TokenSwap {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *TokenSwap) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetSwapAccount sets the "swap" account.
func (inst *TokenSwap) SetSwapAccount(swap ag_solanago.PublicKey) *TokenSwap {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(swap)
	return inst
}

// GetSwapAccount gets the "swap" account.
func (inst *TokenSwap) GetSwapAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetAuthorityAccount sets the "authority" account.
func (inst *TokenSwap) SetAuthorityAccount(authority ag_solanago.PublicKey) *TokenSwap {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(authority)
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *TokenSwap) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetUserTransferAuthorityAccount sets the "userTransferAuthority" account.
func (inst *TokenSwap) SetUserTransferAuthorityAccount(userTransferAuthority ag_solanago.PublicKey) *TokenSwap {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(userTransferAuthority).SIGNER()
	return inst
}

// GetUserTransferAuthorityAccount gets the "userTransferAuthority" account.
func (inst *TokenSwap) GetUserTransferAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetSourceAccount sets the "source" account.
func (inst *TokenSwap) SetSourceAccount(source ag_solanago.PublicKey) *TokenSwap {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(source).WRITE()
	return inst
}

// GetSourceAccount gets the "source" account.
func (inst *TokenSwap) GetSourceAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetSwapSourceAccount sets the "swapSource" account.
func (inst *TokenSwap) SetSwapSourceAccount(swapSource ag_solanago.PublicKey) *TokenSwap {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(swapSource).WRITE()
	return inst
}

// GetSwapSourceAccount gets the "swapSource" account.
func (inst *TokenSwap) GetSwapSourceAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetSwapDestinationAccount sets the "swapDestination" account.
func (inst *TokenSwap) SetSwapDestinationAccount(swapDestination ag_solanago.PublicKey) *TokenSwap {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(swapDestination).WRITE()
	return inst
}

// GetSwapDestinationAccount gets the "swapDestination" account.
func (inst *TokenSwap) GetSwapDestinationAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetDestinationAccount sets the "destination" account.
func (inst *TokenSwap) SetDestinationAccount(destination ag_solanago.PublicKey) *TokenSwap {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(destination).WRITE()
	return inst
}

// GetDestinationAccount gets the "destination" account.
func (inst *TokenSwap) GetDestinationAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetPoolMintAccount sets the "poolMint" account.
func (inst *TokenSwap) SetPoolMintAccount(poolMint ag_solanago.PublicKey) *TokenSwap {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(poolMint).WRITE()
	return inst
}

// GetPoolMintAccount gets the "poolMint" account.
func (inst *TokenSwap) GetPoolMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetPoolFeeAccount sets the "poolFee" account.
func (inst *TokenSwap) SetPoolFeeAccount(poolFee ag_solanago.PublicKey) *TokenSwap {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(poolFee).WRITE()
	return inst
}

// GetPoolFeeAccount gets the "poolFee" account.
func (inst *TokenSwap) GetPoolFeeAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

func (inst TokenSwap) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_TokenSwap,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst TokenSwap) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *TokenSwap) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.MinimumOutAmount == nil {
			return errors.New("MinimumOutAmount parameter is not set")
		}
		if inst.PlatformFeeBps == nil {
			return errors.New("PlatformFeeBps parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.TokenSwapProgram is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Swap is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.UserTransferAuthority is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.Source is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.SwapSource is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.SwapDestination is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.Destination is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.PoolMint is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.PoolFee is not set")
		}
	}
	return nil
}

func (inst *TokenSwap) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("TokenSwap")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=3]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("        InAmount (OPT)", inst.InAmount))
						paramsBranch.Child(ag_format.Param("MinimumOutAmount", *inst.MinimumOutAmount))
						paramsBranch.Child(ag_format.Param("  PlatformFeeBps", *inst.PlatformFeeBps))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=11]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("     tokenSwapProgram", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("         tokenProgram", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("                 swap", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("            authority", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("userTransferAuthority", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("               source", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("           swapSource", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("      swapDestination", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("          destination", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("             poolMint", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("              poolFee", inst.AccountMetaSlice.Get(10)))
					})
				})
		})
}

func (obj TokenSwap) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `InAmount` param (optional):
	{
		if obj.InAmount == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.InAmount)
			if err != nil {
				return err
			}
		}
	}
	// Serialize `MinimumOutAmount` param:
	err = encoder.Encode(obj.MinimumOutAmount)
	if err != nil {
		return err
	}
	// Serialize `PlatformFeeBps` param:
	err = encoder.Encode(obj.PlatformFeeBps)
	if err != nil {
		return err
	}
	return nil
}
func (obj *TokenSwap) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `InAmount` (optional):
	{
		ok, err := decoder.ReadBool()
		if err != nil {
			return err
		}
		if ok {
			err = decoder.Decode(&obj.InAmount)
			if err != nil {
				return err
			}
		}
	}
	// Deserialize `MinimumOutAmount`:
	err = decoder.Decode(&obj.MinimumOutAmount)
	if err != nil {
		return err
	}
	// Deserialize `PlatformFeeBps`:
	err = decoder.Decode(&obj.PlatformFeeBps)
	if err != nil {
		return err
	}
	return nil
}

// NewTokenSwapInstruction declares a new TokenSwap instruction with the provided parameters and accounts.
func NewTokenSwapInstruction(
	// Parameters:
	inAmount uint64,
	minimumOutAmount uint64,
	platformFeeBps uint8,
	// Accounts:
	tokenSwapProgram ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	swap ag_solanago.PublicKey,
	authority ag_solanago.PublicKey,
	userTransferAuthority ag_solanago.PublicKey,
	source ag_solanago.PublicKey,
	swapSource ag_solanago.PublicKey,
	swapDestination ag_solanago.PublicKey,
	destination ag_solanago.PublicKey,
	poolMint ag_solanago.PublicKey,
	poolFee ag_solanago.PublicKey) *TokenSwap {
	return NewTokenSwapInstructionBuilder().
		SetInAmount(inAmount).
		SetMinimumOutAmount(minimumOutAmount).
		SetPlatformFeeBps(platformFeeBps).
		SetTokenSwapProgramAccount(tokenSwapProgram).
		SetTokenProgramAccount(tokenProgram).
		SetSwapAccount(swap).
		SetAuthorityAccount(authority).
		SetUserTransferAuthorityAccount(userTransferAuthority).
		SetSourceAccount(source).
		SetSwapSourceAccount(swapSource).
		SetSwapDestinationAccount(swapDestination).
		SetDestinationAccount(destination).
		SetPoolMintAccount(poolMint).
		SetPoolFeeAccount(poolFee)
}
